/* Hisba — Modern Standard Arabic locale */
import { ar } from './ar.js';

export const arFusha = {
  ...ar,
  language_name: 'العربية الفصحى',
  lang_ar_eg: 'العربية المصرية',
  lang_ar_fusha: 'العربية الفصحى',
  lang_en: 'الإنجليزية',
  nav_help: 'كيفية استخدام التطبيق؟',
  nav_finance: 'المالية',
  nav_insights: 'التحليلات',
  nav_manage: 'الإدارة',
  settings_subtitle: 'إدارة تفضيلاتك',
  profile_name: 'الاسم الظاهر',
  profile_job_title: 'المسمى الوظيفي',
  profile_job_title_optional: 'اختياري',
  profile_email: 'البريد الإلكتروني',
  change_password: 'تغيير كلمة المرور',
  new_password: 'كلمة المرور الجديدة',
  confirm_password: 'تأكيد كلمة المرور',
  save_changes: 'حفظ التغييرات',
  language_region: 'اللغة والمنطقة',
  language_label: 'اختيار اللغة',
  theme_label: 'اختيار المظهر',
  currency_label: 'العملة الافتراضية',
  delete_account_warning: 'سيؤدي هذا إلى حذف حسابك وجميع بياناتك نهائياً',
  setup_before_transaction_title: 'لنجهّز الأساس أولاً',
  setup_before_transaction_desc: 'قبل تسجيل أول معاملة، أضف الحساب والتصنيف اللذين ستستخدمهما لضمان ظهور الرصيد والتقارير بصورة صحيحة.',
  setup_account_missing: 'أضف حساباً نقدياً أو بنكياً أو بطاقة لتسجيل المعاملة وتحديث الرصيد تلقائياً.',
  setup_category_missing: 'أضف تصنيفاً يساعدك على معرفة أوجه إنفاق أموالك.',
  transaction_description: 'الوصف',
  transaction_notes: 'ملاحظات (اختياري)',
};
